Repository finos/compliant-financial-infrastructure, pull requests merged in 2020-12, with the labels that each got.

#86 update meeting minute issue template
  .github/ISSUE_TEMPLATE/Meeting.md
Labels: cla-present

#83 Update CSC WebEx Link to Reflect FINOS Project Calendar
  .github/ISSUE_TEMPLATE/Meeting.md
Labels: cla-present, ready for review

#76 Service Accelerator Template for EKS (Kubernetes) on Amazon AWS
  aws/eks/EKS.md
Labels: aws, cla-present, help wanted, ready for review
