Repository finos/compliant-financial-infrastructure, pull requests merged in 2021-03, with the labels that each got.

#100 Remove Cloud Service Certification Roles No Longer Needed
  docs/open-roles/bdd-test-case-development-role.md
  docs/open-roles/cloud-service-certification-documentation-role.md
  docs/open-roles/cloud-service-effort-owner.md
  docs/open-roles/codified-controls-development-role.md
  docs/open-roles/compliance-framework-mapping-role.md
  docs/open-roles/peer-reviewer-role.md
Labels: cla-present, ready for review

#95 Update project README with CSC logo and CSC wiki homepage content
  README.md
Labels: cla-present, ready for review

#107 Evolving CSC Team Roles, Agile Ceremonies and Sprint Cadence
  docs/agile-workflow/README.md
Labels: cla-present, ready for review

#103 Add Cloud Service Certification Project Maintainer Role
  .gitignore
  docs/open-roles/cloud-service-certification-project-maintainer.md
Labels: cla-present, ready for review

#108 Update Project Operations Manager role link and Maintainer Team reference
  docs/agile-workflow/README.md
Labels: cla-present, ready for review

#109 Add Slack Badge to Cloud Service Certification
  README.md
Labels: cla-present

#98 Terraform IaC for Azure PostgreSQL Single Server with Database and Private Endpoint
  .gitignore
  azure/postgresql/terraform/.gitignore
  azure/postgresql/terraform/README.md
  azure/postgresql/terraform/main.tf
  azure/postgresql/terraform/modules.tf
  azure/postgresql/terraform/modules/postgres/network.tf
  azure/postgresql/terraform/modules/postgres/outputs.tf
  azure/postgresql/terraform/modules/postgres/postgres.tf
  azure/postgresql/terraform/modules/postgres/variables.tf
  azure/postgresql/terraform/outputs.tf
  azure/postgresql/terraform/terraform.tfvars
  azure/postgresql/terraform/variables.tf
Labels: azure, cla-present, help wanted, postgresql, ready for review
