Repository finos/compliant-financial-infrastructure, pull requests merged in 2022-07, with the labels that each got.

#225 Updated our definition of 'compliant' and how it is achieved in CFI
  README.md
Labels: help wanted, ready for review

#224 Updated SAA Template
  templates/ServiceApprovalAcceleratorTemplate.md
Labels: help wanted, ready for review

#232 Changed EKS terraform to use k8s v1.23
  accelerators/kubernetes/eks/tf_cdmc_aws_eks/eks-cluster.tf
Labels: ready for review

#240 Delete S3 control spreadsheet.xlsx
  templates/S3 control spreadsheet.xlsx
Labels: ready for review

#241 Update README.md
  README.md
Labels: ready for review

#216 Feature/pr to bage addition
  .github/actions/status-badge/action.yml
  .github/workflows/aws-eks-verify.yml
  README.md
  docs/_images/bronze.png
  docs/_images/diamond.png
  docs/_images/gold.png
  docs/_images/paper.png
  docs/_images/silver.png
Labels: ready for review, blocked
